# .github/workflows/build.yaml
name: Build
on:
  pull_request:
    branches: [ main ]
    paths:
      - "build.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6.0.0

      - name: Read build version
        id: read_version
        run: |
          echo "$(cat build.txt)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: build-${{ steps.read_version.outputs.build_version }}-x86_64-linux
          path: build.txt
