# .github/workflows/release.yaml
name: Release
on:
  push:
    branches: [ main ]
    paths:
      - "build.txt"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - name: Get Latest Run
        id: get_latest_run
        uses: actions/github-script@v8.0.0
        with:
          script: |
            const { data: runs } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "build.yaml",
            });
            if (runs.total_count === 0) {
              throw new Error("No workflow runs found for build.yaml");
            }
            core.setOutput('id', runs.workflow_runs[0].id);

      - uses: actions/checkout@v6.0.0

      - name: Read build version
        id: read_version
        run: |
          echo "$(cat build.txt)" >> $GITHUB_OUTPUT

      - name: Download artifact from Build workflow
        uses: actions/download-artifact@v6.0.0
        with:
          pattern: build-{{ steps.read_version.outputs.build_version }}-*
          run-id: ${{ steps.get_latest_run.outputs.id }}

      - name: Create release
        uses: softprops/action-gh-release@v2.5.0
        with:
          name: Test release
          tag_name: release-${{ steps.version.outputs.build_version }}
          body: |
            This is a test release created from the Deploy workflow.
          files: ./artifact/build.txt
