# .github/workflows/release.yaml
name: Release
on:
  push:
    branches: [ main ]
    paths:
      - "build.txt"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      build_version: ${{ steps.version.build_version }}
    steps:
      - name: Get plan
        uses: canonical/operator-workflows/internal/get-plan@main
        id: get-plan
        with:
          workflow-file: ".github/workflows/build.yaml"

      - uses: actions/checkout@v6.0.0

      - name: Debug
        run: |
          echo "entire event: ${{ toJson(github.event) }}"
          echo "Workflow Run: ${{ github.event.workflow_run }}"

      - name: Download artifact from Build workflow
        uses: actions/download-artifact@v6.0.0
        with:
          name: build-artifact
          path: ./artifact
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Use artifact
        id: version
        run: |
          cat ./artifact/build.txt >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2.5.0
        with:
          name: Test release
          tag_name: release-${{ steps.outputs.version.build_version }}
          body: |
            This is a test release created from the Deploy workflow.
          files: ./artifact/build.txt
