# .github/workflows/deploy.yml
name: Deploy
on:
  workflow_run:
    workflows: [ Build ]
    types: [ completed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.0

      - name: Download artifact from Build workflow
        uses: actions/download-artifact@v6.0.0
        with:
          name: build-artifact
          path: ./artifact
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Use artifact
        run: cat ./artifact/build.txt

      - name: Create release
        uses: softprops/action-gh-release@v2.5.0
        with:
          name: Test release
          tag_name: release-${{ github.event.workflow_run.id }}
          body: |
            This is a test release created from the Deploy workflow.
          files: ./artifact/build.txt
